name: Deploy static site to Pages

on:
  push:
    branches: ["gh-pages"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Setup pkgx
        uses: pkgxdev/setup@v2
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build site
        run: ./build.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
